### ISSUE TITLE
Container is intermittently stopping with s6-finish TERM and KILL messages

### ISSUE THREAD

**Issue by joshuagrisham** [azinchen/duplicacy#13]
Hi,

I have been using your image for a few months now and I really like the simplicity it brings to a "fire-and-forget" backup solution.
However occasionally I realize that I am no longer getting the backup emails and I have to go and check the status and "give it a kick" (manually start the container again) because it has crashed and stopped for some reason.

Each time this happens, I see this block in `docker logs` for the container:

```
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

Any ideas on the cause and how this can be fixed?  No issues with my other containers, it is only this one which does this. If I had to guess, it seems to do this after a week or two every time.

Thanks!

**Comment by azinchen** [comment]
Hi,

Do you use pre- or post-backup scripts?
