### ISSUE TITLE
[Feature Request] nice level

### ISSUE THREAD

**Issue by esticle** [azinchen/duplicacy#2]
Hi,

Just getting into duplicacy and just a word of thanks first for your container, it is very nice to get everything working and reproducible within minutes, configuring it all with a docker-compose yaml including filters is just fantastic.

Quick feature request - it would be nice to run duplicacy at a particular nice level, so it can only take idle cpu time (as an example).

Nice/Renice is all there and works as expected.

Thanks!

**Comment by azinchen** [comment]
Hi,

Thanks for review!

This project is Docker image around Duplicacy binary. "CPU limit" feature is not implemented in Duplicacy itself. And I don't think think it shall be implemented in image.

I suppose if you need to limit CPU usage of the container you should set appropriate settings for the container. Try to work with CPU settings of Docker container https://docs.docker.com/config/containers/resource_constraints/

**Comment by esticle** [comment]
Hi,

Yep that was going to be my worst-case approach however all I 'really' want is your /app/backup.sh  'duplicati backup' to be called as 'nice -n 19 duplicati backup' ...

I might just utilise cont-init.d and sed something like that in otherwise, thanks!

**Comment by azinchen** [comment]
Let me think about this approach.
