### ISSUE TITLE
backup exit code not captured

### ISSUE THREAD

**Issue by esticle** [azinchen/duplicacy#3]
Hi,

I noticed some of my failed backups are being marked as COMPLETED when it shouldn't be, example:

```
...
Uploaded chunk 4442 size 13353236, 299KB/s 1 day 08:43:07 38.8%
[0] Maximum number of retries reached (backoff: 64, attempts: 15)
Failed to upload the chunk 32a5c7b52d67130c1a5c32c0b5dcbc211cfebze5f59b6214a32ebf8c0921c470: googleapi: Error 403: User rate limit exceeded., userRateLimitExceeded
Backup COMPLETED, duration 21:15:32
```
The issue appears to be due to the way duplicacy is called in _/apps/backup.sh_ :

```
duplicacy $GLOBAL_OPTIONS backup $BACKUP_OPTIONS | tee -a $log_file
exitcode=$?
```
Since _tee_ is being called you are measuring the exitcode by _tee_'s response code and not of duplicacy.

ie. you are doing this:

```
$ exit 1 | tee ; echo $?
0
```

When you can capture the exit code of what is before the pipe with $PIPESTATUS[0] like this:

```
$ exit 1 | tee ; echo ${PIPESTATUS[0]}
1
```

And to get the tee exit code simply:

```
$ exit 1 | tee ; echo ${PIPESTATUS[1]}
0
```
_prune.sh_ appears like it will suffer from the same issue but might be a bit more complicated due to _'sh -c_' being called as well...

**Comment by azinchen** [comment]
Thanks!
