### ISSUE TITLE
Multiple storage destination support?

### ISSUE THREAD

**Issue by BlipRanger** [azinchen/duplicacy#7]
Does this current implementation support having multiple storage destination urls or is it limited to a single one?

**Comment by azinchen** [comment]
Right now this is limited to a single one. But there are several workarounds.

1. `duplicacy add` is not implemented. But there is possible to run it after first run of default container using terminal.
2. `duplicacy copy` is not implemented. Nobody has ever asked.
3. `-storage` option of `duplicacy backup` command is not supported via container setup. But there is possible to define `-storage` option in `BACKUP_OPTIONS` environment variable.

But I suppose, the best solution is to run several `azinchen\duplicacy` containers with one `/data` volume and different `STORAGE_URL` variables.

**Comment by BlipRanger** [comment]
Do you think there be any issue using the "post backup script" to run the add and copy commands?

**Comment by azinchen** [comment]
Not any issue. I haven't tested it.

**Comment by BlipRanger** [comment]
Understood, thanks!
